version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: smartlogix-db
    env_file:
      - ./Credenciales/.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=smartlogix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure

  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file: ./Credenciales/.env
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartlogix-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8084:8084"
    restart: on-failure

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    env_file: ./Credenciales/.env
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartlogix-db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8081"
    restart: on-failure

  shipment-service:
    build: ./shipment-service
    container_name: shipment-service
    env_file: ./Credenciales/.env
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartlogix-db:5432/shipment_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8083:8083"
    restart: on-failure

  order-service:
    build: ./order-service
    container_name: order-service
    env_file: ./Credenciales/.env
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://smartlogix-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8085:8085"
    restart: on-failure

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file: ./Credenciales/.env
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data: