server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    # Ajustado para conectar con el contenedor de la DB
    url: jdbc:postgresql://postgres-db:5432/inventory_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}