server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    # Cambia 'localhost' por 'postgres-db' solo cuando empaquetes todo en Docker
    url: jdbc:postgresql://localhost:5432/inventory_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/